# Generated by Django 3.2.8 on 2021-12-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211129_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pk_id',
        ),
        migrations.AddField(
            model_name='news',
            name='page_visit',
            field=models.IntegerField(default=0),
        ),
    ]
