# Generated by Django 3.2.8 on 2021-12-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table',
            new_name='Contact',
        ),
    ]
