# Generated by Django 3.2.8 on 2021-12-08 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='subject',
        ),
    ]
